/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily:{
        'Estedad-Thin': 'EstedadThin',
        'Estedad-ExtraLight': 'ExtraLight',
        'Estedad-Light': 'Light',
        'Estedad-Regular': 'Regular',
        'Estedad-Medium': 'Medium',
        'Estedad-SemiBold': 'SemiBold',
        'Estedad-Bold': 'Bold',
        'Estedad-ExtraBold': 'ExtraBold',
        'Estedad-Black': 'Black',
      },
      colors: {
        'bg-main': 'var(--bg-main)',
        'bg-box': 'var(--bg-box)',
        'bg-box2': 'var(--bg-box2)',
        'bg-button-orange': 'var(--bg-button-orange)',
        'bg-button-blue': 'var(--bg-button-blue)',
        'bg-button-blue-2': 'var(--bg-button-blue-2)',
        'bg-button-white': 'var(--bg-button-white)',
        'bg-button-green': 'var(--bg-button-green)',
        'bg-gray':'var(--bg-gray)',
        'bg-gray-hover':'(--bg-gray-hover)',
        'bg-button-black': 'var(--bg-button-black)',
        'bg-button-orange2': 'var(--bg-button-orange2)',
        'text-button-orange2': 'var(--text-button-orange2)',
        'text-button-black': 'var(--text-button-black)',
        'text-button-white': 'var(--text-button-white)',
        'text-button-blue': 'var(--text-button-blue)',
        'text-orange': 'var(--text-orange)',
        'title': 'var(--title)',
        'description': 'var(--description)',
        'border-grey': 'var(--border-grey)',
        'border-grey2': 'var(--border-grey2)',
        'bg-circel-blue': 'var(--bg-circel-blue)',
        'bg-circel-green': 'var(--bg-circel-green)',
        'bg-circel-orange': 'var(--bg-circel-orange)',
        'bg-box-advantage': 'var(--bg-box-advantage)',
        'bg-box-download': 'var(--bg-box-download)',
        'bg-section': 'var(--bg-section)',
        'bg-section-purple':'var(--bg-section-purple)',
        'bg-box-purple':'var(--bg-box-purple)',
        'bg-slider': 'var(--bg-slider)',
      },
      boxShadow:{
        'my':'0px 0px 20px 8px #0000000d',
        'my2':'0px -44px 30px 18px #00000018',
        'my3':'0px -35px 20px 13px #00000018',
      },
    },
  },
  plugins: [],
};
