import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/font.css";
import Header from "@/components/templates/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl" className="bg-white">
      <body className={inter.className}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
