// layout.js
import { Inter } from "next/font/google";
import "../globals.css";
import "../../styles/font.css";
import SecondHeader from "@/components/templates/SecondHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <div className="relative w-full min-h-screen overflow-auto flex flex-col justify-start">
          <SecondHeader />
          <div className="w-full h-full flex flex-col flex-grow">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
